# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuberoutectl" do
  version "1.1.1"

  on_macos do
    on_intel do
      sha256 "33c18735a69646b1123c06c41d5f1fa96fbfbae2dff1fc229a199fe76ea5d4d7"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "ff3a7372113f70e93f3d835b0165d62a2db83e8d2e1366bfb56a58987791cc38"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "ef5a4ec274e4593131a617b46ac9b115f7d687775f131457109fef65118e2354"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "29ce52dde95e8ca1ac789e3f46cfb1024114b2890639874a830c2717d56fefe1"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kuberoutectl"
  desc "Provider-agnostic Kubernetes access routing CLI"
  homepage "https://github.com/ymedlop/kuberoutectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kuberoutectl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kuberoutectl"]
    end
  end

  # No zap stanza required

end
