# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuberoutectl" do
  version "1.1.0"

  on_macos do
    on_intel do
      sha256 "e9b3a6dfde6bba9129939ffd1712031dd7822aa4bed84dc626a7109d09390b7f"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "d43f06d4b4f6b3c8481beb00b2dd3e4d3a9f96c48e5d1fc3834588ff03fdd38d"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "775e3d27bef010365a94f2143a8a407fd97ecfea0d3dc647942c0b88d4be02cb"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "9df0e52343ee50dbd25a19f5226bff2f4eeb4d8bc6c660bc54e2692a1c652655"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kuberoutectl"
  desc "Provider-agnostic Kubernetes access routing CLI"
  homepage "https://github.com/ymedlop/kuberoutectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kuberoutectl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kuberoutectl"]
    end
  end

  # No zap stanza required

end
