# This file was generated by GoReleaser. DO NOT EDIT.
cask "kuberoutectl" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "b80095de04248e29c8ba6266320eb7b9d5c8b9d5e35b0b2d952056dc6f56443d"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "0f2cb5d402d561faf855476153b17e0e0e1a1a96edf86861210d98d274cfb2f1"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "0230429e72ff29875e97284806abba6eec7b61d423ea17453e0029858715884b"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "aa70dc2f925eecad39bbb3d41caf3817186a91d206ce4107b33a9d129c355a25"
      url "https://github.com/ymedlop/kuberoutectl/releases/download/v#{version}/kuberoutectl_#{version}_linux_arm64.tar.gz"
    end
  end

  name "kuberoutectl"
  desc "Provider-agnostic Kubernetes access routing CLI"
  homepage "https://github.com/ymedlop/kuberoutectl"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "kuberoutectl"

  postflight do
    if system_command("/usr/bin/xattr", args: ["-h"]).exit_status == 0
      system_command "/usr/bin/xattr", args: ["-dr", "com.apple.quarantine", "#{staged_path}/kuberoutectl"]
    end
  end

  # No zap stanza required

end
