# Rolling development-snapshot cask. Hand-maintained (NOT generated by GoReleaser,
# unlike the stable kuberoutectl.rb). It always points at the mutable
# `development-snapshot` pre-release, whose fixed-name macOS archives are staged
# by kuberoutectl's snapshot-release.yml. version :latest + sha256 :no_check make
# Homebrew re-download on every (re)install, since the URL contents move.
cask "kuberoutectl-snapshot" do
  version :latest
  sha256 :no_check

  arch arm: "arm64", intel: "amd64"

  url "https://github.com/ymedlop/kuberoutectl/releases/download/development-snapshot/kuberoutectl_snapshot_darwin_#{arch}.tar.gz",
      verified: "github.com/ymedlop/kuberoutectl/"
  name "kuberoutectl (development snapshot)"
  desc "Provider-agnostic Kubernetes access routing CLI — rolling development build"
  homepage "https://github.com/ymedlop/kuberoutectl"

  # Rolling build: no upstream version to track.
  livecheck do
    skip "Rolling development snapshot"
  end

  # Can't coexist with the stable cask (same binary name).
  conflicts_with cask: "kuberoutectl"

  binary "kuberoutectl"

  # The binary is unsigned, so macOS quarantines it on install. Clear the
  # quarantine attribute so it runs without a manual `xattr` step — mirrors the
  # stable cask's post-install hook.
  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/kuberoutectl"]
  end

  caveats <<~EOS
    This is a rolling development build from the `development` branch — expect
    breakage. Homebrew will not auto-detect newer snapshots (version is :latest);
    refresh to the current build with:

      brew reinstall ymedlop/tap/kuberoutectl-snapshot

    Use the stable `kuberoutectl` cask for normal use.
  EOS
end
